name: Deploy to dominai.io

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Install opam
      run: sudo apt-get install -y libev-dev opam
    
    - name: Opam init
      run: opam init --bare

    - name: Install Ocaml 4.14.0
      run: opam switch create 4.14.0

    - name: Install opam dependencies
      run: opam install --yes . --deps-only 

    - name: Build server
      run: |
        eval $(opam env)
        dune build src/main.exe

    - name: Move server binary out of artifacts directory
      run: mv _build/default/src/main.exe dominai

    - name: Copy server to EC2
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: 3.225.230.184
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: dominai
        target: /home/ubuntu