name: Deploy to dominai.io

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Install opam
      run: sudo apt-get install -y libev-dev opam
    
    - name: Opam init
      run: opam init

    - name: Install opam dependencies
      run: opam install --yes . --deps-only 

    - name: Build server
      run: |
        eval $(opam env)
        dune build src/main.exe

    - name: Move server binary out of artifacts directory
      run: mv _build/default/src/main.exe dominai